### ISSUE TITLE
Scroll bar doesn't work in edit mode

### ISSUE THREAD

**Issue by joellti** [kepano/obsidian-minimal#11]
When editing a long note spanning multiple pages, I need to use mouse to drag the scroll bar to where I want to be. In preview mode it works fine but in edit mode the scroll bar is present but I can't drag it with my mouse.

I'm on Obsidian Windows version 0.12.4 but I had the same issue with versions before that as well.

**Comment by kepano** [comment]
At first I was not able to replicate this bug. However I think I am seeing it now. However this appears to be a bug in Obsidian because the same issue is present in the default theme.

What I noticed is that when first loading edit mode the scroll bar can't be dragged, but if scroll using the scroll wheel or trackpad then it becomes accessible to drag.

I would recommend reporting this to the Obsidian forum

**Comment by joellti** [comment]
I'm seeing slightly different behavior actually. Firstly, with default theme it works for me in edit mode actually. Secondly, I tried scroll using scroll wheel but the bar is still not draggable after that.

**Comment by kepano** [comment]
Sorry I am not able to replicate the issue on my side. Have you tried disabling your plugins?

**Comment by joellti** [comment]
I tried again with no community plugins enabled at all and only File explorer core plugin enabled but I still got the same behavior. Let me know if you want me to try more.

**Comment by filmgal** [comment]
I realize this issue is closed, but was there ever a fix? I'm seeing the same thing. When in obsidian's "legacy" editor mode, the scrollba can't be selected and moved in any pane that is in "editing" mode. Switch the pane to "reading" mode and it works; go back to editing and it doesn't. 

Works fine when in Obsidian's new "Live Preview" mode, which I still don't want to use yet.

**Comment by kepano** [comment]
Legacy editor is no longer supported in Minimal. You can use Source Editor which is the new replacement for the legacy editor.
