### ISSUE TITLE
Text Labels display error

### ISSUE THREAD

**Issue by KuiyueRO** [kepano/obsidian-minimal#151]
I found this problem when using the Chinese client, tried to switch to multiple languages, and found it was not only Chinese that had this problem.

![image](https://user-images.githubusercontent.com/63145205/150854820-b0af7d95-61cc-469e-8dfb-0484162d81b8.png)

**Comment by kepano** [comment]
This is a known issue due to an Obsidian limitation
https://forum.obsidian.md/t/use-cross-language-identifiers-for-workspace-tabs-for-use-in-theming/31236

Please see release notes
https://github.com/kepano/obsidian-minimal/releases/tag/4.3.0

A translation snippet for Chinese can be found here:
https://github.com/kepano/obsidian-minimal/tree/master/translations

**Comment by kepano** [comment]
Further detail regarding contributions has been added to the Readme:
https://github.com/kepano/obsidian-minimal/blob/master/README.md#contributing

**Comment by KuiyueRO** [comment]
Thanks
