### ISSUE TITLE
Recognising clickable images as images to be included in an image grid. 

### ISSUE THREAD

**Issue by jenshda** [kepano/obsidian-minimal#157]
First of all, thank you for creating this amazing theme. To me the minimal theme IS how Obsidian looks and I could not imagine using another theme. So huge thanks :) This is just a "nice to have" type of request, but one you might not be aware of so I'm just putting it out there. 

**Is your feature request related to a problem? Please describe.**
Using the link function around images will enable using images as *clickable links* to other notes. For example using the image "image.png" as a link to the note "click on this image to get a note" as seen in the code below. 

```markdown
[![[image.png|300]]](<click on this image to get a note>)
```

However, when creating clickable images the image grid function does not work anymore and the images are just fitted after each other. 

**Describe the solution you'd like**
I'd like the minimal theme to recognise the above clickable image as an image to include in the image grid when entering the image grid css-class. 

Again THANKS for all your great work and effort.

**Comment by kepano** [comment]
I agree this would be neat, but it is not possible within the current limitations of Obsidian and Contextual Typography.

To accomplish this in the current way image grids work would at minimum require Contextual Typography to recognize that the link contains an image, and label the parent container accordingly. You can open an issue on the Contextual Typography repo to see if this might something that can be added.

However I suspect this will be a tricky feature to implement for Contextual Typography and for Minimal because of the way Obsidian creates containers around links differently than it does for images.

**Comment by jenshda** [comment]
Ah, I suspected that it might be tricky. Do you think it would be possible if one could use the following containers instead as this would make it more in line with standard Obsidian links?

```markdown
[[click on this image to get a note | ![[image.png]]]]
```

Just so I know if that would solve it before creating any requests.

**Comment by kepano** [comment]
That would not make a difference. The problem is that Obsidian creates a different kind of container around links than around images, so the image grid code doesn't recognize it as an image.
