### ISSUE TITLE
Solarized Light Code Block Selection not working

### ISSUE THREAD

**Issue by kmf** [kepano/obsidian-minimal#166]
Dark mode
![CleanShot 2022-02-01 at 11 56 14](https://user-images.githubusercontent.com/78700/151947833-c11dd041-dc59-44f0-b7d6-ca18540b963a.png)

vs

Solarized Light Code Block Selection
![CleanShot 2022-02-01 at 11 57 32](https://user-images.githubusercontent.com/78700/151947957-3fe6204e-aaa5-47a1-8ca5-c7421cac4f9e.png)

**Comment by kepano** [comment]
It's a bit tricky because the Solarized spec does not provide a color for this context. So the options would be to either invent a new Solarized color, or make code blocks use the main background color, possibly with an outline.

In the meantime you can set a different text selection color using Style Settings.

**Comment by kepano** [comment]
This is fixed as of 5.1.5
