### ISSUE TITLE
Small issue with the Minimal Gruvbox Color Settings

### ISSUE THREAD

**Issue by brimwats** [kepano/obsidian-minimal#167]
Hello!

Just wanted to report an issue with the color settings in the gruvbox settings— when you have the "high" and "low" contrast settings they should follow dark/light0_hard and dark/light0_soft contrast as outline in the schema:
https://github.com/morhetz/gruvbox-contrib/blob/master/color.table —faded bright and neutral are for low high and normal respectively :)

**Comment by kepano** [comment]
I did consider this, however I thought it might be confusing to users. When I initially created that background contrast feature it was for the contrast between the sidebar and the main window — not the contrast between the text and the background.

For now I decided to maintain internal consistency between the color schemes, since I couldn't find any color scheme aside from Gruvbox that has contrast options like this.

I am open to the idea, but I am sure it will upset some people because it would mean removing the high contrast Gruvbox theme with the sidebar in dark mode.

**Comment by brimwats** [comment]
These are fair points! As with everything I incline towards suggesting a toggle for the uber-dark version of the theme, but that would likely disrupt the other schemes you have in Minimal—seems like it would make more sense for you to just recommend anyone who cares very much about the scheme that they should just use Style Settings to achieve that effect—I think that can be done? Either way, you can definitely close this as out of scope—thanks for being open to the feedback!

**Comment by kepano** [comment]
For now my focus will be to continue adding more customizability via Style Settings so people can create their own theme
