### ISSUE TITLE
Different link colors for backlink / outgoing-links  and hyperlink?

### ISSUE THREAD

**Issue by realliyifei** [kepano/obsidian-minimal#174]
I'm always frustrated that I cannot tell the difference between backlink / outgoing-links  and hyperlink by their colors. IMO they’re completely different things and should be visually different too. 

Is there anyway to set them as different colors or other different visual features? (though I doubt the obsidian’s system treats them equally as link and no easy way to distinguish them by just adjusting the theme file)

**Comment by kepano** [comment]
You can use Minimal Theme Settings to separately choose underlining for internal vs external links.

The way Obsidian identifies external vs internal links is quite complicated and still in flux due to the transition to CM6 and Live Preview.

You can develop a snippet using the following as a base
https://github.com/kepano/obsidian-minimal/blob/master/src/scss/features/link-underline.scss

**Comment by realliyifei** [comment]
thanks! that barely suits my needs. Though I think dash underline vs solid underline is more clear

I’m a bit confused where to modify the snippet you mention? Since in local plugin folder I can just find these four files:

<img width="206" alt="image" src="https://user-images.githubusercontent.com/32441766/152714239-a1ddf269-264b-4f57-9b37-fcedbb296185.png">

**Comment by kepano** [comment]
Perhaps a better fit for you would be the Supercharged Links plugin
https://github.com/mdelobelle/obsidian_supercharged_links

If you need help with snippets you can ask in the Obsidian Discord
