### ISSUE TITLE
Text alignment issues after update

### ISSUE THREAD

**Issue by bpdoto** [kepano/obsidian-minimal#291]
**Describe the bug**
In both block quotes and bullets there is a left-alignment issue with text. (see images) 
- In block quotes the first sentence is indented
- In bullets wrapped text does not realign with bullet. This is especially visible with indented bullets

**To reproduce**
see above

**Expected behavior**
Text should align properly as in previous updates

**Screenshots**
First line indented
<img width="501" alt="Screen Shot 2022-05-08 at 8 36 40 AM" src="https://user-images.githubusercontent.com/92997792/167297431-77f7ad4d-dca5-4f6f-a297-34cdb53d07c9.png">

Wrapped text not aligning with bullet
<img width="419" alt="Screen Shot 2022-05-08 at 9 00 50 AM" src="https://user-images.githubusercontent.com/92997792/167297425-a0325807-a061-475e-aeba-e80cd0de2c8a.png">

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.6
	Installer version: v0.14.6
	Operating system: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 21.3.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 3
	Safe mode: off
	Plugins installed: 17
	Plugins enabled: 12
		1: Natural Language Dates
		2: ReadItLater
		3: Style Settings
		4: Homepage
		5: Minimal Theme Settings
		6: Banners
		7: Footnote Shortcut
		8: Mind Map
		9: Collapse All
		10: Dataview
		11: Outliner
		12: Reading Time

**Comment by laawn** [comment]
Also with the Buttons plugin

**Comment by kepano** [comment]
Try updating to 5.2.1 and let me know if this still occurs

**Comment by bpdoto** [comment]
@kepano Right as rain. You're a beast 💪

**Comment by laawn** [comment]
@kepano 
On mobile, code blocks and the Buttons plugin continues to run off the screen. This is fixed by removing the "Readable Length" option in Editor.

Tasks code block...edit button hidden as some tasks run off the screen
![IMG_0588](https://user-images.githubusercontent.com/85444407/167306155-89f91a25-fe5e-4847-9ee2-ef2537546670.jpg)


An embedded search...some results run off the screen
![IMG_0590](https://user-images.githubusercontent.com/85444407/167306158-84129337-b2a2-48c1-9792-45a5b80ede21.jpg)


Buttons plugin
![IMG_0589](https://user-images.githubusercontent.com/85444407/167306157-63afccbe-2700-4934-80ce-3af2e17742b0.jpg)
