### ISSUE TITLE
Option to highlight italic and bolt text

### ISSUE THREAD

**Issue by FalxMuralis** [kepano/obsidian-minimal#329]
I would find it cool if there would be an option to enable highlighted italic and bold text. I am used to the LYT-Theme. It is present there, and I find it easier to find the italic and bold text in my documents.

I would like if there was an option to enable this mentioned highlighting, perhaps in different shades of the accent color, perhaps as a changeable option.

I attach an image of how it looks in the LYT-Theme for reference.
![grafik](https://user-images.githubusercontent.com/91272390/171836693-bd1ea3b5-3bfc-41ce-97c5-ee8c4428b9c8.png)

**Comment by FalxMuralis** [comment]
I learned that you can do this with the [Minimalist Settings](https://github.com/kepano/obsidian-minimal-settings) and the  [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) plugins in combination.
Therefore, Issue closed.

**Comment by qaptoR** [comment]
@FalxMuralis Can you share how you achieved this?

I can only see options for
- bold text color
- italic text color

but I do not see an option in style settings or minimal settings for:
- bold italic text color

It would be very appreciated to have this feature, as it gives an additional level of differentiation when, for example, headings are not appropriate to use as formatting because they conflict with another plugin.

Eg. When using spaced repetition cards, I would like my questions to be formatted with headings, but this causes the path to be shown on the card and therefore with reversed type cards where sometimes the question is shown and I must guess the answer the answer will be shown. 
So the solution is to use bold or italic text for the questions which works fine, but because bold-italic text is the same color as italic text, then I lose an ability to differentiate that style easily.
