### ISSUE TITLE
Refine selections in search

### ISSUE THREAD

**Issue by accept82** [kepano/obsidian-minimal#62]
Improve the selection in the search so that the note that is currently active is highlighted. In my opinion, this is a very convenient function that allows you to work with arrays of information that are selected through a search.
![18-11-2021_00-01_s8768](https://user-images.githubusercontent.com/90281362/142282484-215aaea4-9157-4b1e-bd05-749435017f9b.png)

**Comment by kepano** [comment]
I agree that this would be great, unfortunately it is not possible because Obsidian does not have a CSS class for the active note in Search (same for Starred). 

You will need to make this feature request from the Obsidian team via the Obsidian forum. I suspect this already exists as a feature request.

**Comment by accept82** [comment]
Good day! Thanks for the answer! The function is really useful I will write in Obsidian
