### ISSUE TITLE
Longform: Clicking the fold indicator in the Scenes Sidebar doesn't fold items

### ISSUE THREAD

**Issue by vishae** [kepano/obsidian-minimal#627]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.1.2

### Describe the bug

Longform allows you to arrange your writing project in nested scenes(files):

<img width="486" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/6110232/40ba6694-09a6-403d-844e-c0d4299f1e11">

## Expected Behaviour
When I click on the folding indicator, I expect the nested items to fold up (the screenshot is from the default theme):
<img width="444" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/6110232/76e52e99-9847-4a66-96db-7909b6bf7240">

## Actual Behaviour
When I click on the indicator, the nested items disappear from view, but the space they occupy remains:
<img width="434" alt="image" src="https://github.com/kepano/obsidian-minimal/assets/6110232/73e35af2-d88b-40f6-8549-c32aad4d6c2e">

I have tested this in a completely empty vault with all the plugins disabled except for Longform, and the issue persists.

### Debug info

SYSTEM INFO:
	Obsidian version: v1.4.2
	Installer version: v1.2.8
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 22.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.1.2
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 69
	Plugins enabled: 49
		1: Obsidian42 - BRAT v0.7.0
		2: Admonition v9.3.3
		3: Advanced Mobile Toolbar v1.8.0
		4: Advanced Tables v0.19.1
		5: Advanced URI v1.37.0
		6: Better Command Palette v0.15.0
		7: Better Word Count v0.10.0
		8: Bullet Journal++ v0.0.1
		9: Buttons v0.4.19
		10: Calendar v1.5.10
		11: Collapse All v2.0.0
		12: Dataview v0.5.56
		13: Dice Roller v9.3.0
		14: Dynamic Table of Contents v0.0.27
		15: Editor Syntax Highlight v0.1.3
		16: Enhancing Mindmap v0.2.5
		17: Highlightr v1.2.2
		18: Hotkey Helper v0.3.18
		19: Icon Folder v2.1.2
		20: Icons v0.3.0
		21: Longform v2.0.3
		22: macOS Keyboard Navigation v1.1.2
		23: Metadata Extractor v1.1.0
		24: MetaEdit v1.8.2
		25: Mind Map v1.1.0
		26: Minimal Theme Settings v6.3.2
		27: Multi-line Formatting v0.4.1
		28: MySnippets v1.2.3
		29: Natural Language Dates v0.6.1
		30: Outliner v4.8.0
		31: Paste URL into selection v1.7.1
		32: Periodic Notes v0.0.17
		33: QuickAdd v1.2.1
		34: Recent Files v1.3.7
		35: Settings Search v1.3.8
		36: Snippetor v0.4.4
		37: Sort & Permute lines v0.7.0
		38: Sortable v0.3.1
		39: Style Settings v1.0.6
		40: Table Extended v1.6.1
		41: Table of Contents v0.2.0
		42: Tag Wrangler v0.5.11
		43: Tasks v4.5.0
		44: Templater v1.16.0
		45: Vantage - Advanced search builder v1.4.2
		46: Toggle Meta Yaml v1.2.0
		47: Notes dater v1.0.1
		48: Homepage v3.4
		49: Typewriter Mode v0.0.1

**Comment by squareyed** [comment]
I have this problem too. I've tried many other themes in the past few weeks because of this, and none of them have this problem, only Minimal. I love Minimal, and am not happy with any of the other themes, but this is a deal breaker for me. 

Although you can't see the sub-scenes, you can blindly click on them and drag them into other places. I can't trust myself not to do something like that without noticing. 

My images are from a fresh sandbox with only Minimal and Longform installed.  

Longform project unfolded:
![Longform with minimal - fold problem - UNfolded](https://github.com/kepano/obsidian-minimal/assets/100071910/2b0f7e33-ec6e-4a9b-b221-e5bb8ea7ab01)

Longform project folded showing empty spaces that should have folded away:
![Longform with minimal - fold problem - folded](https://github.com/kepano/obsidian-minimal/assets/100071910/f2dc1343-08f7-48a7-8ce7-2f7d9b690f6a)

I'm really hoping this is an easy fix, since it seems to work everywhere else.

**Comment by squareyed** [comment]
This is working now for me with Minimal 7.4.7 and Longform 2.0.4

Wonderful!
