### ISSUE TITLE
Relationship Lines does not fully extend from the bullet

### ISSUE THREAD

**Issue by ernest67** [kepano/obsidian-minimal#74]
Not sure whether this is a bug or not. I have been using minimal theme since late September. Since early November, the relationship line does not fully extend from the bullet (i.e. there is space between the bullet and the relationship line)

Before:
![Screenshot 2021-12-11 at 21 42 13](https://user-images.githubusercontent.com/95947701/145678839-18088ec5-efb2-400b-9997-79af6d730167.png)

Now:
![Screenshot 2021-12-11 at 21 44 51](https://user-images.githubusercontent.com/95947701/145678964-75a20087-1fb0-406d-9c63-319e2ae5987e.png)

Was wondering whether it is intended or is it just a problem that I am having, as I prefer the older version more.

I have tried disabling all other plug-ins but the problem still persist. 

Once again, I really appreciate you making this awesome theme and taking the time to solve our issues, thank you and enjoy your day!

**Comment by kepano** [comment]
This is an intentional change introduced in 4.0.6. I agree that it would be nicer if the lines could extend as they did before, unfortunately the old styling caused a bug in Obsidian when switching between Edit and Preview — using the old relationship lines would result in the scroll position changing. I have not found a solution to get the full relationship lines that doesn’t cause the scroll bug.

**Comment by kepano** [comment]
This issue should be moved to the [indentation guides plugin](https://github.com/mgmeyers/obsidian-indentation-guides) as I am migrating Minimal away from its own relationship lines code.
