### ISSUE TITLE
Title width does not match content width in live preview mode.

### ISSUE THREAD

**Issue by meetcw** [kepano/obsidian-minimal#78]
Environment:
Operating System: ArchLinux
Obsidian Version: v.0.13.14

![Peek 2021-12-24 00-01](https://user-images.githubusercontent.com/13930715/147264877-9e0e05b6-f298-45a7-a96a-8b2d76675678.gif)

**Comment by kepano** [comment]
Do you have "Folding offset" setting matched to your folding settings?

**Comment by meetcw** [comment]
"Folding offset" option is disabled in my settings.

**I found some possible reasons:**

The "Normal line width" option is not active in "live preview" mode.
![image](https://user-images.githubusercontent.com/13930715/147355686-6566008e-a65a-46d4-953b-f21c9d929df1.png)


The `.view-header-title-container` element has a fixed width. When i disable "Editor>Readable line length", it doesn't look good.

![image](https://user-images.githubusercontent.com/13930715/147353734-f529149d-6f95-4e40-aa4e-ca767bd10e3b.png)

**Comment by F4ded** [comment]
I have a temporary solution here.
You can edit the `Minimal.css` and change the 'width' to `var(--max-width)`: 
![image](https://user-images.githubusercontent.com/66620626/147443534-74b540a6-2b21-47c5-a609-ee8f0559225a.png)
Save, then reopen Obsidian, and the title will match the content in live preview mode:
![image](https://user-images.githubusercontent.com/66620626/147443657-71a94ab6-8645-4a3c-9448-8ad63ffa9558.png)

**Comment by kepano** [comment]
> The "Normal line width" option is not active in "live preview" mode.

I made a change to address this issue, should be fixed if you download the latest.

My other recommendations:

1. If you have "Fold heading" and/or "Fold indent" active in Obsidian > Editor settings, make sure you also turn on "Folding offset" in Minimal Settings. If you have Fold headings/indent turned off, please also turn off Folding offset in Minimal Settings.
2. I would not recommend turning off Readable line length — if you want a long line length it is preferable to customize your line length in the Minimal Settings so that the title and body match.
