### ISSUE TITLE
Width of editor is now more wider than before

### ISSUE THREAD

**Issue by nicosomb** [kepano/obsidian-minimal#782]
### Is the bug present when using the default Obsidian theme?

No

### Is the bug present when snippets and plugins are disabled?

Yes

### Minimal theme version

7.7.18

### Describe the bug

Before the last updates, the editor size was less wider. I can't find the setting to fix that. 
Is that related to a recent update? 

### Debug info

SYSTEM INFO:
	Obsidian version: v1.7.1
	Installer version: v1.6.3
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 23.5.0
	Login status: logged in
	Language: fr
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.7.18
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 14
		1: Templater v2.4.2
		2: Calendar v1.5.10
		3: Smart Typography v1.0.18
		4: Longform v2.0.7
		5: Trash Explorer v1.2.2
		6: Novel word count v3.10.2
		7: Find orphaned files and broken links v1.10.1
		8: Minimal Theme Settings v8.1.1
		9: Rapid Notes v1.2.5
		10: Hide Folders v1.5.1
		11: Multi Properties v1.1.2
		12: Share Note v0.8.15
		13: Hider v1.5.1
		14: Style Settings v1.0.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
You can change this setting in **Minimal Theme Settings** → **Typography** → **Normal line width**

The issue is not a bug, but a fix related to [Obsidian 1.7.1](https://obsidian.md/changelog/2024-08-27-desktop-v1.7.1/). This version of Obsidian fixes an issue that has been present for a long time: "REM units are now synced with the base font size."

Previously when you changed the main font size your line width setting no longer matched (approximately 40 characters by default). Now your line width setting should correctly match your font size.

**Comment by nicosomb** [comment]
Perfect. Thank you so much for your great work.
