### ISSUE TITLE
Text labels for primary navigation?

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal#94]
Is this new feature supposed to to work with iPadOS? If yes, I’m not seeing it.
![F0C166A3-22E2-48DC-9701-929E396EEB2A](https://user-images.githubusercontent.com/80698092/147795815-fc0aefc1-7342-448e-9c0f-5553898f9895.jpeg)

**Comment by kepano** [comment]
No, this is desktop only as Obsidian for iPad OS already already has labeled primary navigation but it is handled differently (via nested navigation).

**Comment by davebhc71** [comment]
Thank you for the quick reply! Keep up the great work.

***@***.*** (coffee supporter 😉)

**Comment by davebhc71** [comment]
One more thing. If I have one of the other options opened as it’s own Pane, the label doesn’t show. Certainly not a game changer! Just another ‘nit’ for nitpickers like me.

**Comment by kepano** [comment]
Can you share an example?

**Comment by davebhc71** [comment]
Here it is-

**Comment by kepano** [comment]
I am not seeing anything on my end. I don't think attachments work when you reply via email.

You can share the screenshot on the issue [in Github itself](https://github.com/kepano/obsidian-minimal/issues/94), or send me the name of the pane or plugin you are trying to use.

**Comment by davebhc71** [comment]
![IMG_0486](https://user-images.githubusercontent.com/80698092/147833179-fbdfcb23-233c-4306-8c68-932c2217cc4c.jpeg)

**Comment by davebhc71** [comment]
Just copied to Git

**Comment by kepano** [comment]
Oh I see! Yes this is intentional. In earlier versions the feature did affect all the panes in the left sidebar, but people complained about that so I have it only affecting the first set of tabs.

I think if you want to make it work as you describe, a snippet might be the best solution for now.

If you remove `:nth-child(3)` from this snippet it should work as you expect
https://github.com/kepano/obsidian-minimal/blob/master/snippets/nav-labels.css

**Comment by davebhc71** [comment]
👍, but that’s above my pay grade. I’ll live with it…
